# Nom de votre projet
name: 'dbt_project'
version: '1.0.0'

# Profile de connexion (BigQuery, etc.)
profile: 'my_dbt_project'

# Configuration des chemins
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configurer les modèles avec des datasets spécifiques
models:
  dbt_project:
    staging:
      +materialized: view
      +dataset: staging  # Dataset spécifique pour les modèles de staging
    marts:
      +materialized: table
      +dataset: marts  # Dataset spécifique pour les modèles de marts